best_args = {
    'seq-cifar10': {
                    'our': {200: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'wd_reg': 0.00001,
                                  'batch_size': 32,
                                  'n_epochs': 100,
                                  'alpha': 1,
                                  'beta': 0.4},
                            500: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'wd_reg': 0.00001,
                                  'batch_size': 32,
                                  'n_epochs': 100,
                                  'alpha': 1,
                                  'beta': 0.4},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'wd_reg': 0.00001,
                                   'batch_size': 32,
                                   'n_epochs': 100,
                                   'alpha': 1,
                                   'beta': 0.4}},
                    },
}
